config/routes.rb
ApiDocumentor::Application.routes.draw do
  # Home page
  root to: "projects#index"
  
  # Admin pages
  scope "admin", module: "admin" do
    resources :projects, as: :admin_projects
    resources :api_types, as: :admin_api_types
    resources :method_types, as: :admin_method_types
  end
  
  # API pages
  get "/projects/:project_slug"                            => "projects#show", as: :project_page
  get "/projects/:project_slug/apis/:id"                   => "api_types#show", as: :api_type_page
  get "/projects/:project_slug/apis/:api_id/methods/:id"   => "method_types#show", as: :method_type_page
  
  # Static pages
  get "/http-response-codes"                               => "static_files#http_response_codes"
  get "/tos"                                               => "static_files#tos", as: :tos
end

app/controllers/admin/api_types_controller.rb
class Admin::ApiTypesController < Admin::ApplicationController
  cache_sweeper :api_type_sweeper, only: [:create, :update, :destroy]
  
  def index
    if params[:project_id]
      @api_types = ApiType.where(:project_id => params[:project_id]).order("name ASC")
    else
      @api_types = ApiType.all
    end
  end

  def show
    @api_type = ApiType.find(params[:id])
  end

  def new
    @api_type = ApiType.new(project_id: params[:project_id])
  end

  def create
    @api_type = ApiType.new(params[:api_type])
    if @api_type.save
      redirect_to admin_api_type_path(@api_type), :notice => "Successfully created api."
    else
      render :action => 'new'
    end
  end

  def edit
    @api_type = ApiType.find(params[:id])
  end

  def update
    @api_type = ApiType.find(params[:id])
    if @api_type.update_attributes(params[:api_type])
      redirect_to admin_api_type_path(@api_type), :notice  => "Successfully updated api."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @api_type = ApiType.find(params[:id])
    @api_type.destroy
    redirect_to admin_api_types_url, :notice => "Successfully destroyed api."
  end
end

app/controllers/api_types_controller.rb
class ApiTypesController < ApplicationController
  # Cache static page
  caches_page :show
  
  def show
    @api_type = Project.find_by_slug(params[:project_slug]).api_types.where(:id => params[:id]).first
  end
end

app/views/admin/api_types/_form.html.erb
<%= form_for [:admin, @api_type] do |f| %>
  <%= f.hidden_field :project_id %>
  <div class="field">
    <%= f.label :name %>:
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn primary" %>
  </div>
<% end %>

app/views/admin/api_types/edit.html.erb
<div class="row">
  <div class="span16">
    <div class="page-header">
      <h2>Edit API</h2>
      <p>Edit the API details.</p>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/admin/api_types/new.html.erb
<div class="row">
  <div class="span16">
    <div class="page-header">
      <h2>New Api</h2>
      <p>Create a new API for the project.</p>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/admin/api_types/show.html.erb
<div class="row">
  <div class="span16">
    <div class="page-header">
      <h2><%= @api_type.name %> // <small><%=link_to "(/) Edit", edit_admin_api_type_path %> | 
      <%= link_to "(x) Destroy", admin_api_type_path(@api_type), :method => :delete, :confirm => "Are you sure?" %></small></h2>
      <p>
        Project: <%= link_to @api_type.project.name, admin_project_path(@api_type.project) %>        
      </p>
    </div>
    <div>
      <h3>Methods</h3>
      <table class="zebra-striped">
        <thead>
          <tr>
            <th>HTTP M.</th>
            <th>Name</th>
            <th>Url</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @api_type.method_types.each do |method_type| %>
          <tr>
            <td><%= method_type.http_method%></td>
            <td><%= method_type.name%></td>
            <td><%= method_type.url%></td>
            <th>
              <%=link_to "(?) Show", admin_method_type_path(method_type) %> | 
              <%=link_to "(/) Edit", edit_admin_method_type_path(method_type) %> | 
              <%= link_to "(x) Destroy", admin_method_type_path(method_type), :method => :delete, :confirm => "Are you sure?" %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%=link_to "Add a new Method", new_admin_method_type_path(:api_type_id => @api_type.id) %>

    </div>
    
  </div>
</div>