config/routes.rb
ApiDocumentor::Application.routes.draw do
  # Home page
  root to: "projects#index"
  
  # Admin pages
  scope "admin", module: "admin" do
    resources :projects, as: :admin_projects
    resources :api_types, as: :admin_api_types
    resources :method_types, as: :admin_method_types
  end
  
  # API pages
  get "/projects/:project_slug"                            => "projects#show", as: :project_page
  get "/projects/:project_slug/apis/:id"                   => "api_types#show", as: :api_type_page
  get "/projects/:project_slug/apis/:api_id/methods/:id"   => "method_types#show", as: :method_type_page
  
  # Static pages
  get "/http-response-codes"                               => "static_files#http_response_codes"
  get "/tos"                                               => "static_files#tos", as: :tos
end

app/models/project.rb
class Project < ActiveRecord::Base
  # relations
  has_many :api_types,    inverse_of: :project
  has_many :method_types, through:    :api_types
  
  # validations
  validates_presence_of :name
  validates_uniqueness_of :slug
  
  # accessors
  attr_accessible :name, :description
  
  # actions
  before_create :set_slug
  
  # get slug
  def set_slug
    self.slug = self.name.parameterize
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  cache_sweeper :project_sweeper, only: [:create, :update, :destroy]
  
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to admin_project_path(@project), :notice => "Successfully created project."
    else
      render :action => 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to admin_project_path(@project), :notice  => "Successfully updated project."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admin_projects_url, :notice => "Successfully destroyed project."
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # Cache static page
  caches_page :show
  
  def show
    @project = Project.find_by_slug(params[:project_slug])
  end
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  <div class="field">
    <%= f.label :name %>:
    <%= f.text_field :name %>
  </div>
  <hr />
  <div class="field">
    <%= f.label :description %>:
    <%= f.text_area :description, :cols => 80, :rows => 7 %>  
  </div>
  <hr />
  <div class="actions">
    <%= f.submit :class => "btn primary" %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<div class="row">
  <div class="span16">
    <div class="page-header">
      <h2>Edit project</h2>
      <p>Edit API project details.</p>
    </div>
    <%= render "form" %>
    </div>
</div>

app/views/admin/projects/index.html.erb
<table class="zebra-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, admin_project_path(project) %></td>
      <td><%= project.slug%></td>
      <td><%= project.created_at%></td>
      <th>
        <%=link_to "(/) Edit", edit_admin_project_path(project) %> | 
        <%= link_to "(x) Destroy", admin_project_path(project), :method => :delete, :confirm => "Are you sure?" %>
      </th>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="actions">
  <%=link_to "Create a new project", new_admin_project_path %>
</div>

app/views/admin/projects/new.html.erb
<div class="row">
  <div class="span16">
    <div class="page-header">
      <h2>New project</h2>
      <p>Create a new API project.</p>
    </div>
      <%= render "form" %>
  </div>
</div>

app/views/admin/projects/show.html.erb
<div class="row">
  <div class="span16">
    <div class="page-header">
      <h2><%= @project.name %> // <small><%=link_to "(/) Edit", edit_admin_project_path %> | 
      <%= link_to "(x) Destroy", admin_project_path(@project), :method => :delete, :confirm => "Are you sure?" %></small></h2>
      <p><%= @project.description %></p>

    </div>
    <div>
      <h3>APIs</h3>
      <table class="zebra-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Methods</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @project.api_types.order("name ASC").each do |api_type| %>
          <tr>
            <td><%= link_to api_type.name, admin_api_type_path(api_type) %></td>
            <td><%= api_type.method_types.map {|mt| mt.name}.join(" / ")%></td>
            <th>
              <%= link_to "(/) Edit", edit_admin_api_type_path(api_type) %> | 
              <%= link_to "(x) Destroy", admin_api_type_path(api_type), :method => :delete, :confirm => "Are you sure?" %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%=link_to "Add a new API", new_admin_api_type_path(:project_id => @project.id) %>
    // 
    <%= link_to "(L) View all projects", admin_projects_path %>
  </div>
</div>