config/routes.rb
ApiDocumentor::Application.routes.draw do
  # Home page
  root to: "projects#index"
  
  # Admin pages
  scope "admin", module: "admin" do
    resources :projects, as: :admin_projects
    resources :api_types, as: :admin_api_types
    resources :method_types, as: :admin_method_types
  end
  
  # API pages
  get "/projects/:project_slug"                            => "projects#show", as: :project_page
  get "/projects/:project_slug/apis/:id"                   => "api_types#show", as: :api_type_page
  get "/projects/:project_slug/apis/:api_id/methods/:id"   => "method_types#show", as: :method_type_page
  
  # Static pages
  get "/http-response-codes"                               => "static_files#http_response_codes"
  get "/tos"                                               => "static_files#tos", as: :tos
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield :meta %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application" %>
    <link href="http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/">Dakick API</a>
          <ul class="nav">
            <%= yield :topbar_nav %>
          </ul>
        </div>
      </div>
    </div>
    
    <div class="container">
      <%= yield %>
      <footer>
        <p><span><%= link_to "Terms of service", tos_path %></span> - &copy; <%=AppConfig["copyright"]%>  <span class="pull-right">// powered by <a href="https://github.com/dakick/apidocumentor">api document(o|e)r</span></p>
      </footer>
    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.js"></script>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-16133327-2']);
      _gaq.push(['_setDomainName', '.dakick.com']);
      _gaq.push(['_trackPageview']);
      setTimeout('_gaq.push([\'_trackEvent\', \'NoBounce\', \'Over 30 seconds\'])',30000);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </body>
</html>